### ISSUE TITLE
Support pushing to blender api endpoint

### ISSUE THREAD

**Issue by XertroV** [nicoell/tm-editor-route#1]
I created [a PR](https://github.com/codecat/tm-editor-trails/pull/11) a while ago for editor trails that would push trails to blender. I know skyslide would appreciate it if you supported the format we developed (it's live in blendermania atm). Happy to help with porting.

to find relevant code in the diff, ctrl+f for `Setting_UploadTrailsURL`

**Comment by nicoell** [comment]
Thanks for the link. I'll have a look when I look at JSON import/export to support your format.
