### ISSUE TITLE
properly match style to chosen overlay style

### ISSUE THREAD

**Issue by ezio416** [nicoell/tm-editor-route#2]
It seems you're doing something custom with how the window looks, namely with how everything is very boxey and feels quite cramped. It would be nice to have default styling that I'm already very accustomed to. The tabs for `General` and `Display` don't show which one is selected, the corners are very sharp when they should be rounded with this style, checkboxes are a different color, resizing the window makes a yellow border instead of default, and I'm sure there are some other things I haven't noticed yet. I also happen to use the `Next` style which the plugin mostly matches, but for those who use another style, it just doesn't match at all.

Some icons on the bottom are a bit cut off to the bottom and the scrubber bar is cut off to the right - I imagine this is because of my 1.5x UI scaling.

<img width="631" alt="Screenshot 2024-01-31 122051" src="https://github.com/nicoell/tm-editor-route/assets/37951898/5da159da-1898-4d5a-8c3f-2d99ba37198f">

**Comment by nicoell** [comment]
Plugin has its custom style. I'll look into an option to disable the custom style, but I need to fix some UI size calculations for that.

**Comment by nicoell** [comment]
Fixed in https://github.com/nicoell/tm-editor-route/commit/fc0ddcf58166496cea056266cefb61f08b248bc3 
Change will be available in v0.9.2 Beta

**Comment by ezio416** [comment]
Thank you so much! Looks a lot better in my opinion and the palette options are nice too
