### ISSUE TITLE
X button does nothing

### ISSUE THREAD

**Issue by ezio416** [nicoell/tm-editor-route#3]
Small issue but the X button at the top of the window to close it does not close it. This is usually due to a mis-parametered `UI::Begin()`

In addition to this, I don't see any way to close this window besides toggling the plugin entirely which is not ideal

**Comment by nicoell** [comment]
Fixed in https://github.com/nicoell/tm-editor-route/commit/fc0ddcf58166496cea056266cefb61f08b248bc3 
Change will be available in v0.9.2 Beta
