### ISSUE TITLE
Mouse scroll on the scroll bar of the route ids will move the camera up/down in the editor

### ISSUE THREAD

**Issue by gjkf** [nicoell/tm-editor-route#4]
Scrolling the mouse wheel over the route ids list and then moving the cursor outside the window, will cause the editor camera to move up/down as if the scrolling was done in the editor itself.

**Comment by nicoell** [comment]
I will check if I can do sth. to prevent this.
In case you know a solution for it, feel free to share :)

**Comment by nicoell** [comment]
I could not find a way to fix this. The same behavior happens in other plugins, too.
